# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QhyperSpectral
                                 A QGIS plugin
 This plugin import and analyze hyper spectral data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-02-14
        copyright            : (C) 2024 by DMN Solutions
        email                : michel.nzikou@alumni.uleth.ca
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QhyperSpectral class from file QhyperSpectral.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qhyper_spectral import QhyperSpectral
    return QhyperSpectral(iface)
